# Generated by Django 3.0.7 on 2020-08-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortify', '0006_auto_20200810_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='user',
            field=models.CharField(max_length=64),
        ),
    ]
