# Generated by Django 3.0.7 on 2020-08-10 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortify', '0008_auto_20200810_1039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_account',
        ),
    ]
